---
#
# Ansible managed
#
repository:
  description: Install and configure vault_auditdevice on your system.
  homepage: https://robertdebock.nl/
  topics: vaultauditdevice, infrastructure, security, ansible, molecule, tox, playbook
