---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Read /root/.vault-token
      ansible.builtin.slurp:
        src: /root/.vault-token
      register: vault_auditdevice_token_slurped

  roles:
    - role: robertdebock.vault_auditdevice
      vault_auditdevice_ssl_verify: false
      vault_auditdevice_token: "{{ vault_auditdevice_token_slurped['content'] | b64decode }}"
      vault_auditdevice_list:
        - name: local_file/  # Make sure the value is trailed by a `/`.
          type: file
          description: File Audit Device
          options:
            file_path: /opt/vault/vault_audit.log
