---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if /opt/vault/vault_audit.log exists
      ansible.builtin.stat:
        path: /opt/vault/vault_audit.log
      register: vault_audit_log
      failed_when:
        - not vault_audit_log.stat.exists
